version: '3.8'

services:
  app:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Map port 8000 on your machine to port 8000 in the container
    ports:
      - "9090:9090"
    # Load environment variables from the .env file
    env_file:
      - .env
