version: '3'
services:
  agent-servers:
    build: .
    env_file:
      - .env
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
    volumes:
      - C:/Users/dasei/genai-agentos/backend:/app/backend
      - C:/Users/dasei/genai-agentos/cli:/app/cli
    environment:
      - PYTHONPATH=/app
    command: python /app/cli/agents/full_stack_agent/a2a_server.py
    tty: true
    stdin_open: true
